language: haxe

haxe:
    - "4.1.1"
    - "4.0.5"
    - "3.4.7"

install:
    - haxelib install hxcpp
    - haxelib install utest

script:
    - haxelib dev jsoni18n .
    - cd tests
    - haxe -main Main -lib jsoni18n -lib utest -cpp build
    - cd build
    - ./Main
